'use client';
import { useState } from 'react';
import { where } from 'firebase/firestore';
import { call } from '@/lib/firebase';
import { Row } from '@/lib/types';
import { dateLabel,timeLabel,asDate,errorMessage,downloadCSV } from '@/lib/utils';
import { Button,Notice,PageHeading,Loading,Empty,Modal } from '../ui';
import { usePaged,Pagination,Status } from './data';
export function AdminBookings(){const [status,setStatus]=useState(''),[member,setMember]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[exporting,setExporting]=useState(false);const data=usePaged('bookings','date',[...(status?[where('status','==',status)]:[]),...(member?[where('userId','==',member)]:[])],`${status}:${member}`);async function action(name:string,row:Row,extra={}){setBusy(row.id);setError('');try{await call(name,{bookingId:row.id,...extra});}catch(e){setError(errorMessage(e));}finally{setBusy('');}}return <><PageHeading title="Bookings."/><div className="admin-toolbar"><input className="search-input" aria-label="Filter by member ID" placeholder="Filter by member ID" value={member} onChange={e=>setMember(e.target.value)}/><label className="field">Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['confirmed','completed','cancelled','no-show'].map(s=><option key={s}>{s}</option>)}</select></label><Button className="secondary" onClick={()=>setExporting(true)}>Export CSV</Button></div>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="table-wrap"><table><thead><tr><th>Member</th><th>Class</th><th>Session</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.rows.map(b=><tr key={b.id}><td>{b.userId}</td><td>{b.className}</td><td>{dateLabel(b.date)}<br/><span className="muted">{timeLabel(b.date)} PT</span></td><td><Status row={b}/></td><td><div className="row">{b.status==='confirmed'&&<>{asDate(b.endAt)<=new Date()&&<><Button className="small" disabled={busy===b.id} onClick={()=>action('markBookingCompleted',b,{status:'completed'})}>Present</Button><Button className="secondary small" disabled={busy===b.id} onClick={()=>action('markBookingCompleted',b,{status:'no-show'})}>No-show</Button></>}<Button className="text small" disabled={busy===b.id} onClick={()=>{const reason=window.prompt('Cancellation reason');if(reason)action('cancelBooking',b,{reason});}}>Cancel</Button></>}</div></td></tr>)}</tbody></table></div>:<Empty>No matching bookings.</Empty>}<Pagination data={data}/>{exporting&&<ExportDialog collection="bookings" onClose={()=>setExporting(false)}/>}</>;}
export function ExportDialog({collection,onClose}:{collection:'bookings'|'payments';onClose:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <Modal title="Export CSV" onClose={onClose}><form className="stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const result=await call<{csv:string;filename:string}>('exportBookingsCSV',{collection,from:new Date(String(f.get('from'))).toISOString(),to:new Date(+new Date(String(f.get('to')))+86400000).toISOString()});downloadCSV(result.csv,result.filename);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><label className="field">From<input name="from" type="date" required/></label><label className="field">Through<input name="to" type="date" required/></label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Download CSV</Button></form></Modal>;}
