'use client';
import { FormEvent,useState } from 'react';
import { where,orderBy,limit } from 'firebase/firestore';
import { call } from '@/lib/firebase';
import { useRows } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { dateLabel,money,errorMessage } from '@/lib/utils';
import { Button,Notice,PageHeading,Loading,Empty,Modal } from '../ui';
import { usePaged,Pagination } from './data';
export function AdminMembers(){const [search,setSearch]=useState(''),[selected,setSelected]=useState<Row|null>(null),[adding,setAdding]=useState(false);const email=search.includes('@');const data=usePaged('users','fullName',search?[where(email?'email':'fullName','>=',search),where(email?'email':'fullName','<=',search+'\uf8ff')]:[],search);return <><PageHeading title="Members."/><div className="admin-toolbar"><input className="search-input" aria-label="Search member name or email" placeholder="Name prefix or email" value={search} onChange={e=>setSearch(e.target.value)}/><Button onClick={()=>setAdding(true)}>Add Member</Button></div>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Credits</th><th>Role</th><th>Joined</th><th>Status</th><th>Manage</th></tr></thead><tbody>{data.rows.map(u=><tr key={u.id}><td>{u.fullName}</td><td>{u.email}</td><td>{u.sessionsRemaining} <span className="muted">({u.sessionsReserved||0} reserved)</span></td><td>{u.role}</td><td>{dateLabel(u.memberSince)}</td><td>{u.isActive?'Active':'Inactive'}</td><td><Button className="secondary small" onClick={()=>setSelected(u)}>View / Edit</Button></td></tr>)}</tbody></table></div>:<Empty>No members found.</Empty>}<Pagination data={data}/>{selected&&<MemberEditor member={selected} onClose={()=>setSelected(null)}/>} {adding&&<AddMember onClose={()=>setAdding(false)}/>}</>;}
function AddMember({onClose}:{onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title="Add Member" onClose={onClose}><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await call('addMember',Object.fromEntries(new FormData(e.currentTarget)));onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><label className="field">Full name<input name="fullName" required maxLength={100}/></label><label className="field">Email<input name="email" required type="email"/></label><label className="field">Phone<input name="phone" type="tel"/></label><p className="muted" style={{fontSize:12}}>The member receives an account setup email when email delivery is enabled.</p>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Create Member</Button></form></Modal>;}
function MemberEditor({member,onClose}:{member:Row;onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const bookings=useRows('bookings',[where('userId','==',member.id),orderBy('date','desc'),limit(20)],member.id),payments=useRows('payments',[where('userId','==',member.id),orderBy('createdAt','desc'),limit(20)],member.id);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);try{await call('updateMember',{userId:member.id,fullName:f.fullName,isActive:f.isActive==='on',role:f.role,creditAdjustment:Number(f.creditAdjustment),reason:f.reason});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}return <Modal title={member.fullName} onClose={onClose}><p className="muted" style={{fontSize:12}}>Member ID: {member.id}</p><form className="stack" onSubmit={save}><label className="field">Full name<input name="fullName" required defaultValue={member.fullName}/></label><label className="field">Role<select name="role" defaultValue={member.role}><option>member</option><option>coach</option><option>admin</option></select></label><label className="check-field"><input name="isActive" type="checkbox" defaultChecked={member.isActive}/>Account active</label><label className="field">Credit adjustment · current balance {member.sessionsRemaining}<input name="creditAdjustment" type="number" min="-1000" max="1000" defaultValue="0" required/></label><label className="field">Reason for changes<input name="reason" required minLength={3} maxLength={500}/></label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Save Member</Button></form><h3 style={{marginTop:30}}>Recent bookings</h3>{bookings.rows.map(b=><p key={b.id} style={{fontSize:12}}>{dateLabel(b.date)} · {b.className} · {b.status}</p>)}<h3>Recent payments</h3>{payments.rows.map(p=><p key={p.id} style={{fontSize:12}}>{dateLabel(p.createdAt)} · {money(p.amount)} · {p.status}</p>)}</Modal>;}
