'use client';
import { FormEvent,useState } from 'react';
import { doc,setDoc,serverTimestamp,writeBatch } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useRows } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { errorMessage,money } from '@/lib/utils';
import { Button,Notice,PageHeading,Modal,Loading } from '../ui';
export function AdminPlans(){const data=useRows('membershipPlans'),[selected,setSelected]=useState<Row|null>(null),[drag,setDrag]=useState(''),[error,setError]=useState('');const rows=[...data.rows].sort((a,b)=>a.sortOrder-b.sortOrder);async function move(from:string,to:string){if(from===to)return;const next=[...rows],index=next.findIndex(p=>p.id===from),target=next.findIndex(p=>p.id===to);if(index<0||target<0)return;const [item]=next.splice(index,1);next.splice(target,0,item);const batch=writeBatch(db);next.forEach((p,i)=>batch.update(doc(db,'membershipPlans',p.id),{sortOrder:i}));try{await batch.commit();}catch(e){setError(errorMessage(e));}}return <><PageHeading title="Membership Plans."/><div className="admin-toolbar"><Button onClick={()=>setSelected({id:''})}>Create Plan</Button><span className="muted" style={{fontSize:12}}>Drag cards or use the arrows to change the display order.</span></div>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:<div className="stack">{rows.map((p,i)=><article draggable onDragStart={()=>setDrag(p.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(drag,p.id)} className="card row spread" key={p.id}><div><h3>{p.name}</h3><p className="muted" style={{margin:0}}>{money(p.price)} · {p.sessionCount??p.creditsPerPurchase} credits · {p.isActive?'Active':'Inactive'}</p></div><div className="row"><Button className="text small" aria-label={`Move ${p.name} up`} disabled={i===0} onClick={()=>move(p.id,rows[i-1].id)}>↑</Button><Button className="text small" aria-label={`Move ${p.name} down`} disabled={i===rows.length-1} onClick={()=>move(p.id,rows[i+1].id)}>↓</Button><Button className="secondary small" onClick={()=>setSelected(p)}>Edit</Button></div></article>)}</div>}{selected&&<PlanEditor row={selected} order={rows.length} onClose={()=>setSelected(null)}/>}</>;}
function PlanEditor({row,order,onClose}:{row:Row;order:number;onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);const price=Math.round(Number(f.price)*100),credits=Number(f.credits);try{await setDoc(doc(db,'membershipPlans',row.id||crypto.randomUUID()),{name:f.name,description:f.description,price,priceLabel:money(price).replace('.00',''),perSessionLabel:f.perSessionLabel,sessionCount:f.planType==='package'?credits:null,creditsPerPurchase:credits,planType:f.planType,isRecommended:f.isRecommended==='on',isActive:f.isActive==='on',sortOrder:row.sortOrder??order,createdAt:row.createdAt||serverTimestamp(),updatedAt:serverTimestamp()});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}return <Modal title={row.id?'Edit Plan':'Create Plan'} onClose={onClose}><form className="stack" onSubmit={save}>{[['name','Plan name'],['description','Description'],['perSessionLabel','Rate description']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} defaultValue={row[key]||''} required/></label>)}<div className="field-grid"><label className="field">Price in USD<input name="price" type="number" min="0.50" step="0.01" required defaultValue={row.price?row.price/100:''}/></label><label className="field">Session credits<input name="credits" type="number" min="1" max="1000" required defaultValue={row.sessionCount??row.creditsPerPurchase??1}/></label></div><label className="field">Type<select name="planType" defaultValue={row.planType||'package'}><option value="package">Session package</option><option value="hourly">Hourly</option></select></label><label className="check-field"><input name="isRecommended" type="checkbox" defaultChecked={row.isRecommended}/>Recommended</label><label className="check-field"><input name="isActive" type="checkbox" defaultChecked={row.isActive!==false}/>Active</label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Save Plan</Button></form></Modal>;}
