'use client';
import { FormEvent,useState } from 'react';
import { doc,setDoc,serverTimestamp,writeBatch } from 'firebase/firestore';
import { ref,uploadBytes,getDownloadURL } from 'firebase/storage';
import { db,storage } from '@/lib/firebase';
import { useRows } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { errorMessage,money } from '@/lib/utils';
import { Button,Notice,PageHeading,Modal,Loading } from '../ui';
export function AdminStore(){const data=useRows('products'),[selected,setSelected]=useState<Row|null>(null),[drag,setDrag]=useState(''),[error,setError]=useState('');const rows=[...data.rows].sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0));async function move(from:string,to:string){if(from===to)return;const next=[...rows],index=next.findIndex(p=>p.id===from),target=next.findIndex(p=>p.id===to);if(index<0||target<0)return;const [item]=next.splice(index,1);next.splice(target,0,item);const batch=writeBatch(db);next.forEach((p,i)=>batch.update(doc(db,'products',p.id),{sortOrder:i}));try{await batch.commit();}catch(e){setError(errorMessage(e));}}return <><PageHeading title="Store." eyebrow="Products"/><div className="admin-toolbar"><Button onClick={()=>setSelected({id:''})}>Add Product</Button><span className="muted" style={{fontSize:12}}>Drag cards or use the arrows to change the display order.</span></div>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:<div className="stack">{rows.map((p,i)=><article draggable onDragStart={()=>setDrag(p.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(drag,p.id)} className="card row spread" key={p.id}><div className="row">{p.imageUrl&&<img src={p.imageUrl} alt="" style={{width:48,height:48,objectFit:'cover',borderRadius:8}}/>}<div><h3>{p.name}</h3><p className="muted" style={{margin:0}}>{money(p.price)} · {p.isActive?'Active':'Inactive'}</p></div></div><div className="row"><Button className="text small" aria-label={`Move ${p.name} up`} disabled={i===0} onClick={()=>move(p.id,rows[i-1].id)}>↑</Button><Button className="text small" aria-label={`Move ${p.name} down`} disabled={i===rows.length-1} onClick={()=>move(p.id,rows[i+1].id)}>↓</Button><Button className="secondary small" onClick={()=>setSelected(p)}>Edit</Button></div></article>)}{rows.length===0&&<p className="muted">No products yet. Add your first one.</p>}</div>}{selected&&<ProductEditor row={selected} order={rows.length} onClose={()=>setSelected(null)}/>}</>;}
function ProductEditor({row,order,onClose}:{row:Row;order:number;onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[imageUrl,setImageUrl]=useState(row.imageUrl||'');async function uploadImage(file:File|undefined){if(!file)return;if(file.size>=5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG or WebP smaller than 5 MB.');return;}setBusy(true);setError('');try{const id=row.id||crypto.randomUUID();const target=ref(storage,`gym/products/${id}`);await uploadBytes(target,file,{contentType:file.type});setImageUrl(await getDownloadURL(target));if(!row.id)row.id=id;}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');const price=Math.round(Number(f.price)*100);try{await setDoc(doc(db,'products',row.id||crypto.randomUUID()),{name:f.name,description:f.description,price,priceLabel:money(price),imageUrl,isActive:f.isActive==='on',sortOrder:row.sortOrder??order,createdAt:row.createdAt||serverTimestamp(),updatedAt:serverTimestamp()});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}return <Modal title={row.id?'Edit Product':'Add Product'} onClose={onClose}><form className="stack" onSubmit={save}><label className="field">Product photo{imageUrl&&<img src={imageUrl} alt="" style={{width:96,height:96,objectFit:'cover',borderRadius:8,marginBottom:8}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>uploadImage(e.target.files?.[0])}/></label>{[['name','Product name'],['description','Description']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} defaultValue={row[key]||''} required={key==='name'}/></label>)}<label className="field">Price in USD<input name="price" type="number" min="0.50" step="0.01" required defaultValue={row.price?row.price/100:''}/></label><label className="check-field"><input name="isActive" type="checkbox" defaultChecked={row.isActive!==false}/>Active</label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Save Product</Button></form></Modal>;}
