'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, GoogleAuthProvider, updateProfile, sendPasswordResetEmail, sendEmailVerification } from 'firebase/auth';
import { doc, serverTimestamp, updateDoc } from 'firebase/firestore';
import { auth, db, call } from '@/lib/firebase';
import { errorMessage } from '@/lib/utils';
import { Button, Notice } from './ui';
export function AuthForm({signup=false}:{signup?:boolean}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),router=useRouter();
  function onward(){const next=new URLSearchParams(window.location.search).get('next');router.push(next?.startsWith('/')&&!next.startsWith('//')?next:'/dashboard');}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;try{if(signup){const result=await createUserWithEmailAndPassword(auth,data.email,data.password);await updateProfile(result.user,{displayName:data.fullName});await call('initializeProfile');await updateDoc(doc(db,'users',result.user.uid),{fullName:data.fullName,phone:data.phone,childName:data.childName,childAge:Number(data.childAge),updatedAt:serverTimestamp()});await sendEmailVerification(result.user);}else{await signInWithEmailAndPassword(auth,data.email,data.password);await call('initializeProfile');}onward();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function google(){setBusy(true);setError('');try{await signInWithPopup(auth,new GoogleAuthProvider());await call('initializeProfile');onward();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <div className="auth-panel card"><p className="eyebrow">Your corner is waiting</p><h1>{signup?'Start your journey.':'Welcome back.'}</h1><p className="muted">{signup?'Create your family’s account and take the first step.':'Sign in to keep your training moving.'}</p>{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<form onSubmit={submit}>{signup&&<label className="field">Full name<input name="fullName" required maxLength={100} autoComplete="name"/></label>}<label className="field">Email<input id="auth-email" name="email" required type="email" autoComplete="email"/></label>{signup&&<label className="field">Phone<input name="phone" required type="tel" pattern="[+0-9 ()-]{7,32}" autoComplete="tel"/></label>}<label className="field">Password<input name="password" required type="password" minLength={signup?8:1} autoComplete={signup?'new-password':'current-password'}/></label>{signup?<><div className="field-grid"><label className="field">Participant name<input name="childName" required maxLength={100}/></label><label className="field">Participant age<input name="childAge" required type="number" min="1" max="120"/></label></div><label className="check-field"><input type="checkbox" required/>I am an adult registering myself or a child in my care.</label><p className="muted" style={{fontSize:12}}>By creating an account, you agree to the <Link href="/terms">Terms</Link> and <Link href="/privacy">Privacy Policy</Link>.</p></>:<button className="button text small" type="button" onClick={async()=>{const email=(document.getElementById('auth-email') as HTMLInputElement).value;try{await sendPasswordResetEmail(auth,email);setMessage('Password reset email sent.');}catch(e){setError(errorMessage(e));}}}>Forgot password?</button>}<Button busy={busy}>{signup?'Create Account':'Sign In'} →</Button></form><Button className="secondary" style={{marginTop:16}} disabled={busy} onClick={google}>Continue with Google</Button><p className="switch-auth">{signup?'Already have an account?':'New here?'} <Link href={signup?'/signin':'/signup'}>{signup?'Sign In':'Get Started'}</Link></p></div>;
}
