'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Elements, PaymentElement, useElements, useStripe } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import { useSearchParams } from 'next/navigation';
import { call } from '@/lib/firebase';
import { errorMessage } from '@/lib/utils';
import { Button, Notice, Loading, PageHeading, ActionLink } from './ui';
import { MemberShell } from './member-pages';
import { useAuth } from './providers';
const stripePromise=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY):null;
export function Checkout(){const search=useSearchParams(),planId=search.get('plan')||'ten',{user}=useAuth(),[secret,setSecret]=useState(''),[error,setError]=useState(''),[complete,setComplete]=useState(false);useEffect(()=>{if(!user||!stripePromise)return;let active=true;const key=`checkout:${user.uid}:${planId}`;let requestId=sessionStorage.getItem(key);if(!requestId){requestId=crypto.randomUUID();sessionStorage.setItem(key,requestId);}call<{clientSecret?:string;status:string}>('createPaymentIntent',{planId,requestId}).then(r=>{if(!active)return;if(r.status==='completed'){setComplete(true);sessionStorage.removeItem(key);}else if(r.clientSecret)setSecret(r.clientSecret);else setError('This checkout is no longer available. Start a new checkout.');}).catch(e=>{if(active)setError(errorMessage(e));});return()=>{active=false;};},[user,planId]);return <MemberShell><PageHeading title="Your next chapter."/> {!stripePromise?<Notice>Online payments are not available yet. Contact the gym to purchase a plan.</Notice>:error?<Notice error>{error}</Notice>:complete?<><Notice>This payment is complete. Your membership is updated.</Notice><ActionLink href="/membership">View Membership</ActionLink></>:secret?<Elements stripe={stripePromise} options={{clientSecret:secret,appearance:{theme:'night',variables:{colorPrimary:'#E50914',colorBackground:'#181818'}}}}><CheckoutForm planId={planId}/></Elements>:<Loading/>}</MemberShell>;}
function CheckoutForm({planId}:{planId:string}){const stripe=useStripe(),elements=useElements(),{user}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!stripe||!elements)return;setBusy(true);const result=await stripe.confirmPayment({elements,confirmParams:{return_url:`${window.location.origin}/membership`},redirect:'if_required'});if(result.error)setError(result.error.message||'Payment was not completed.');else{sessionStorage.removeItem(`checkout:${user!.uid}:${planId}`);setSuccess(true);}setBusy(false);}return <form className="card stack" style={{maxWidth:600}} onSubmit={submit}><PaymentElement/>{error&&<Notice error>{error}</Notice>}{success?<><Notice>Payment submitted. Your session balance updates when payment is confirmed.</Notice><ActionLink href="/membership">View Membership</ActionLink></>:<Button busy={busy} disabled={!stripe}>Pay Securely →</Button>}</form>;}
